'''
  Partially generated by GPT (02/07/2025).
'''
import matplotlib.pyplot as plt
import numpy as np
import os
import matplotlib.font_manager as fm

plt.rcParams.update({
    'font.family': 'Times New Roman'
})
for font in fm.findSystemFonts(fontpaths=None, fontext='ttf'):
    if "Libertine_R" in font:
        font_prop = fm.FontProperties(fname=font)
        font_name = font_prop.get_name()
        plt.rcParams.update({
            'font.family': font_name
        })

def read_results(result_path):
    if not os.path.exists(result_path):
        raise FileNotFoundError("Experimental results not found!")
    global get_neighbor_latency
    global two_hop_latency
    global bfs_latency
    global sssp_latency
    global pr_latency
    global wcc_latency
    methods = os.listdir(result_path)
    for method in methods:
        print("Processing", method)
        method_path = os.path.join(result_path, method)
        method_path = os.path.join(method_path, "analytics")
        idx = 0
        if method == 'teseo.13':
            idx = 0
        elif method == 'sortledton.4':
            idx = 1
        elif method == 'bvgt':
            idx = 2
        elif method == 'gtx':
            idx = 3
        elif method == 'radixgraph':
            idx = 4
        else:
            continue
        for file in os.listdir(method_path):
            print("Processing file", file)
            idx2 = 0
            if file.startswith("dota-league"):
                idx2 = 0
            elif file.startswith("graph500-24"):
                idx2 = 1
            elif file.startswith("uniform-24"):
                idx2 = 2
            else:
                continue
            with open(os.path.join(method_path, file), "r") as f:
                lines = f.readlines()
                for line in lines:
                    if line.startswith("Get 1-hop"):
                        tm = line.split()[8]
                        if line.split()[-1] == "ms":
                            get_neighbor_latency[idx][idx2] = int(tm)
                        else:
                            tm = tm.split(":")
                            multiple = 1
                            for i in range(len(tm) - 1, -1, -1):
                                get_neighbor_latency[idx][idx2] += float(tm[i]) * multiple
                                multiple *= 60
                                get_neighbor_latency[idx][idx2] *= 1000
                    if line.startswith("Get 2-hop"):
                        tm = line.split()[8]
                        if line.split()[-1] == "ms":
                            two_hop_latency[idx][idx2] = int(tm)
                        else:
                            tm = tm.split(":")
                            multiple = 1
                            for i in range(len(tm) - 1, -1, -1):
                                two_hop_latency[idx][idx2] += float(tm[i]) * multiple
                                multiple *= 60
                                two_hop_latency[idx][idx2] *= 1000
                    if line.startswith(">> BFS N:"):
                        tm = line.split()[5].rstrip(",")
                        bfs_latency[idx][idx2] = int(tm) / 1000
                    if line.startswith(">> SSSP N:"):
                        tm = line.split()[5].rstrip(",")
                        sssp_latency[idx][idx2] = int(tm) / 1000
                    if line.startswith(">> PageRank N:"):
                        tm = line.split()[5].rstrip(",")
                        pr_latency[idx][idx2] = int(tm) / 1000
                    if line.startswith(">> WCC N:"):
                        tm = line.split()[5].rstrip(",")
                        wcc_latency[idx][idx2] = int(tm) / 1000
                    
# Example data
datasets = ['dota', 'g24', 'u24']
methods = ['Teseo', 'Sortledton', 'Spruce', 'GTX', 'RadixGraph']
get_neighbor_latency = [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
]
two_hop_latency = [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
]
bfs_latency = [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
]
sssp_latency = [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
]
pr_latency = [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
]
wcc_latency = [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
]
read_results("./results")

# Colors and hatch patterns for each method
colors = ['steelblue', 'orange', 'green', 'red', 'purple']
hatches = ['/', '\\', 'x', '-', 'o']

def plot(throughputs, output_path):
    # Plotting setup
    x = np.arange(len(datasets))  # Label locations
    width = 0.15  # Width of each bar

    fig, ax = plt.subplots(figsize=(10, 4))

    # Plot each method's bars
    for i, (method, color, hatch) in enumerate(zip(methods, colors, hatches)):
        offset = (i - 2) * width  # Center the bars
        ax.bar(x + offset, throughputs[i], width, label=method, color=color, hatch=hatch, edgecolor='black')

    # Axes labels and ticks
    ax.set_ylabel('Latency (ms)', fontsize=20, fontweight='bold')
    # ax.set_xlabel('Datasets', fontsize=20, fontweight='bold')
    ax.set_yscale('log')
    ax.set_xticks(x)
    ax.tick_params(axis='y', labelsize=18)
    ax.set_xticklabels(datasets, fontsize=18)
    ax.legend(loc='lower center', bbox_to_anchor=(0.5, 1.02), columnspacing=0.5, fontsize=20, ncol=5)
    ax.grid(True, axis='y', linestyle='--', alpha=0.7)

    plt.tight_layout()
    plt.savefig(output_path)

plot(get_neighbor_latency, "./get-neighbor.pdf")
plot(two_hop_latency, "./two-hop.pdf")
plot(bfs_latency, "./bfs.pdf")
plot(sssp_latency, "./sssp.pdf")
plot(pr_latency, "./pr.pdf")
plot(wcc_latency, "./wcc.pdf")