'''
  Partially generated by GPT (30/09/2025).
'''
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
import matplotlib.font_manager as fm

plt.rcParams.update({
    'font.family': 'Times New Roman'
})
for font in fm.findSystemFonts(fontpaths=None, fontext='ttf'):
    if "Libertine_R" in font:
        font_prop = fm.FontProperties(fname=font)
        font_name = font_prop.get_name()
        plt.rcParams.update({
            'font.family': font_name
        })
                    
# Example data
datasets = ['lj', 'dota', 'orkut', 'g24', 'u24', 'twitter']
methods = ['Teseo', 'Sortledton', 'Spruce', 'GTX', 'RadixGraph']

# Colors and hatch patterns for each method
cs = plt.colormaps['tab10']
colors = [cs(i) for i in range(len(methods))]
hatches = ['/', '\\', 'x', '-', 'o']

captions = [
    "(a) 1-hop neighbor queries",
    "(b) 2-hop neighbor queries",
    "(c) BFS latency",
    "(d) SSSP latency",
    "(e) PR latency",
    "(f) WCC latency",
    "(g) TC latency",
    "(h) BC latency"
]

# ==================================
# Load CSVs
# ==================================
get_neighbor_throughput_df = pd.read_csv("csv/get_neighbor_throughput.csv")
two_hop_neighbor_throughput = pd.read_csv("csv/two_hop_throughput.csv")
bfs_latency = pd.read_csv("csv/bfs_latency.csv")
sssp_latency = pd.read_csv("csv/sssp_latency.csv")
pr_latency = pd.read_csv("csv/pr_latency.csv")
wcc_latency = pd.read_csv("csv/wcc_latency.csv")
tc_latency = pd.read_csv("csv/lcc_latency.csv")
bc_latency = pd.read_csv("csv/bc_latency.csv")

# Drop last nan column
get_neighbor_throughput_data = get_neighbor_throughput_df.iloc[:, 1:-1].values  # shape: (num_methods, num_datasets)
two_hop_neighbor_throughput_data = two_hop_neighbor_throughput.iloc[:, 1:-1].values
bfs_latency_data = bfs_latency.iloc[:, 1:-1].values
sssp_latency_data = sssp_latency.iloc[:, 1:-1].values
pr_latency_data = pr_latency.iloc[:, 1:-1].values
wcc_latency_data = wcc_latency.iloc[:, 1:-1].values
tc_latency_data = tc_latency.iloc[:, 1:-1].values
bc_latency_data = bc_latency.iloc[:, 1:-1].values

# ==================================
# Plot helpers
# ==================================
def plot(ax, data, ylabel, log=False):
    x = np.arange(len(datasets))
    width = 0.15  # bar width

    for i, (method, color, hatch) in enumerate(zip(methods, colors, hatches)):
        offset = (i - (len(methods) - 1) / 2) * width
        ax.bar(x + offset, data[i], width,
               label=method, color=color, hatch=hatch, edgecolor="black")

    ax.set_ylabel(ylabel, fontsize=30, fontweight="bold")
    ax.set_xticks(x)
    ax.set_xticklabels(datasets, fontsize=25)
    ax.tick_params(axis="y", labelsize=25)
    ax.grid(True, axis="y", linestyle="--", alpha=0.7)

    if log:
        ax.set_yscale("log")

if not os.path.exists("./figures"):
    os.makedirs("./figures")
# ==================================
# Make 2×4 plots
# ==================================
fig, axes = plt.subplots(2, 4, figsize=(35, 10), sharey=False)
axes = axes.flatten()

for idx, (ax, caption) in enumerate(zip(axes, captions), start=1):
    if idx == 1:  # 1-hop neighbor
        plot(ax, get_neighbor_throughput_data, ylabel="Throughput (qops)", log=True)
    elif idx == 2:  # 2-hop neighbor
        plot(ax, two_hop_neighbor_throughput_data, ylabel="Throughput (qops)", log=True)
    elif idx == 3:  # bfs
        plot(ax, bfs_latency_data, ylabel="Latency (ms)", log=True)
    elif idx == 4:  # sssp
        plot(ax, sssp_latency_data, ylabel="Latency (ms)", log=True)
    elif idx == 5:  # pr
        plot(ax, pr_latency_data, ylabel="Latency (ms)", log=True)
    elif idx == 6:  # wcc
        plot(ax, wcc_latency_data, ylabel="Latency (ms)", log=True)
    elif idx == 7:  # tc
        plot(ax, tc_latency_data, ylabel="Latency (ms)", log=True)
    elif idx == 8:  # bc
        plot(ax, bc_latency_data, ylabel="Latency (ms)", log=True)
    ax.set_xlabel(caption, fontsize=30, fontweight="bold", labelpad=15)

# Shared legend at top
handles, labels = axes[0].get_legend_handles_labels()
fig.legend(handles, labels,
           loc="upper center",           # center horizontally
           ncol=len(methods), fontsize=35)

plt.tight_layout(rect=[0, 0, 1, 0.85])  # leave space for the legend
plt.savefig("figures/combined_plots3.pdf")